title: Noah Fage
description: "CS student at McGill, focused on detection engineering."
url: "https://noah-fage.github.io"
author: Noah Fage
linkedin: noah-fage-139885209
github: noah-fage

markdown: kramdown
permalink: /writing/:title/
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - .gitignore
